### ISSUE TITLE
Still a lot of v1 and malariamine content in the v2 biotestmine tutorial

### ISSUE THREAD

**Issue by sammyjava** [intermine/im-docs#28]
If I didn't know IM I'd be completely confused by the mixture of v1 and v2 instructions, referencing malariamine and biotestmine, in the tutorial. Please delete/retype or go over with fine-toothed comb. It's currently utterly confusing to a newbie.

**Comment by yochannah** [comment]
Hey Sam!

I'm working through the v2 tutorial at the moment and trying to iron out the kinks (there are quite a few!). If I let you know once I'm done can you look again and tell me if you think I've missed anything?

Yo

**Comment by yochannah** [comment]
Ok, I've managed to successfully run through the entire http://intermine.readthedocs.io/en/intermine-2.0/get-started/tutorial/ and I _think_ I've removed all or most of the bugs I encountered on the way, with a bunch of help from @julie-sullivan 

I've also searched and replaced any mention of MalariaMine found here: http://intermine.readthedocs.io/en/intermine-2.0/get-started/tutorial/webapp/ and put biotestmine instead, to make things more consistent. There are still some any commands here and in other places that I'm not sure how to update so I'll leave this ticket open.

**Comment by sammyjava** [comment]
Looks good to me! Only issue on tutorial/webapp, which I'm sure you're aware of, is the use of the MalariaMine images for the header configuration section, rather than BiotestMine.
