### ISSUE TITLE
Add a copy button next to code examples

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/im-docs#30]
It would be nice to have a copy button beside code examples in our docs. 
https://sphinx-copybutton.readthedocs.io/en/latest/

**Comment by yochannah** [comment]
I've added the hacktoberfest label to this issue - newcomers are welcome to help out with this issue! 

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by asherpasha** [comment]
I have submitted a pull request. (I am also a newcomer).

**Comment by yochannah** [comment]
This works perfectly - thanks @asherpasha for yet another stellar contribution!!
