### ISSUE TITLE
Typo in the tutorial

### ISSUE THREAD

**Issue by JinHuan95** [intermine/im-docs#41]
https://intermine.readthedocs.io/en/latest/get-started/tutorial/

For installation of SOLR, the last command misses an 'x' at the end
~/git/biotestmine $ ./gradlew postprocess -Pprocess=create-autocomplete-inde .

**Comment by Persdre** [comment]
yes you are right

**Comment by Persdre** [comment]
already updated it!

**Comment by amycruz97** [comment]
is this issue still open for PR

**Comment by Anisha-28** [comment]
Can i work on this issue @JinHuan95

**Comment by uosl** [comment]
Sorry, I see that the typo has been fixed a while ago. Thank you for showing interest!
