### ISSUE TITLE
Web documentation has multiple links linking to the same page

### ISSUE THREAD

**Issue by IamMujuziMoses** [intermine/im-docs#51]
![Screenshot (150)](https://user-images.githubusercontent.com/49279842/97309092-a647e500-1872-11eb-92c1-cfb244313b72.png)
![Screenshot (149)](https://user-images.githubusercontent.com/49279842/97309116-acd65c80-1872-11eb-984e-ade87f346244.png)

Those are some of the multiple links linking to the same page.

**Comment by danielabutano** [comment]
Thanks @IamMujuziMoses for spot and fixed it.
