### ISSUE TITLE
Add search box

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/im-docs#7]
@kkarra wants a search box that searches the docs at read-the-docs. 

This would be different from the search box we hope to add that queries the intermines themselves.

**Comment by KukkadapuSushma** [comment]
Hi,

I see that there's a Quick Search box on the docs main page : 

![image](https://user-images.githubusercontent.com/14278142/36983146-a407d404-20b7-11e8-89f3-ea5eda9daeaa.png)


So, is the issue about the same search box or a different one??
@julie-sullivan

**Comment by julie-sullivan** [comment]
Yes, read the docs has a search box. 

@kkarra do you remember what you asked for? I don't! 

If not, I am going to close this ticket!

**Comment by kkarra** [comment]
I think I might have been referring to the search box being a click away rather than on home page ;-) 
The new home page (intermine.org) looks great!   
Can be closed.
