### ISSUE TITLE
The search should only point to the version of  the documentation I'm reading

### ISSUE THREAD

**Issue by danielabutano** [intermine/im-docs#70]
If I search for web service I have 3 suggestions returned. The first is related to next, the second to 4.0.0 and only the last to the current directory.
Is it possible to only show the links related to the version I'm. So if I'm reading 5.0.0, I want the result pointing to the 5.0.0, If i'am reading the 4.0.0 the result point to the 4.0.0

**Comment by SanniM3** [comment]
Done.
