### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by danielabutano** [intermine/im-docs#77]
- Add link to the intermine.org
- Check if the contect is ok

**Comment by Hina-softwareEngineer** [comment]
Hi, I am new to open source and want to contribute to intermine.  I know about javascript and React js. and want to learn more and give back to the community. Can you please elaborate the above list a little bit more. I want to work on this issue to get started. or are there any javascript related repositories on which I can work?

**Comment by uosl** [comment]
Hello @Hina-softwareEngineer 
Sorry, this seems to already have been done. (You can see http://intermine.org/im-docs/ that the navbar has a link to intermine.org.)
